%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                          %
%	       Mondi salvati		   %
%                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

section(mondi_salvati).
% Mondi pre-generati per rappresentare diverse situazioni

pred(carica_mondo(atom)).
% carica_mondo(X): Carica in base dati dinamica il mondo X
% MODO: (+) semidet
carica_mondo(mondo1) :-
	retractall(size(_)),
	retractall(mondo(_)),
	assert(size(5)),
	assert(mondo(c(p(1, 1), foresta, []))),
	assert(mondo(c(p(1, 2), foresta, []))),
	assert(mondo(c(p(1, 3), foresta, []))),
	assert(mondo(c(p(1, 4), deserto, [magnete]))),
	assert(mondo(c(p(1, 5), mare, []))),
	assert(mondo(c(p(2, 1), deserto, []))),
	assert(mondo(c(p(2, 2), deserto, [magnete]))),
	assert(mondo(c(p(2, 3), mare, []))),
	assert(mondo(c(p(2, 4), foresta, [carro]))),
	assert(mondo(c(p(2, 5), deserto, [magnete]))),
	assert(mondo(c(p(3, 1), cielo, []))),
	assert(mondo(c(p(3, 2), mare, []))),
	assert(mondo(c(p(3, 3), cielo, []))),
	assert(mondo(c(p(3, 4), cielo, []))),
	assert(mondo(c(p(3, 5), cielo, []))),
	assert(mondo(c(p(4, 1), foresta, [carro]))),
	assert(mondo(c(p(4, 2), foresta, [magnete]))),
	assert(mondo(c(p(4, 3), mare, []))),
	assert(mondo(c(p(4, 4), deserto, [magnete]))),
	assert(mondo(c(p(4, 5), foresta, [magnete]))),
	assert(mondo(c(p(5, 1), cielo, []))),
	assert(mondo(c(p(5, 2), cielo, []))),
        assert(mondo(c(p(5, 3), deserto, [aereo]))),
	assert(mondo(c(p(5, 4), mare, []))),
	assert(mondo(c(p(5, 5), foresta, []))).

carica_mondo(mondo2) :-
	retractall(size(_)),
	retractall(mondo(_)),
	assert(size(5)),
	assert(mondo(c(p(1, 1), foresta, []))),
	assert(mondo(c(p(1, 2), foresta, []))),
	assert(mondo(c(p(1, 3), foresta, [aereo]))),
	assert(mondo(c(p(1, 4), deserto, [magnete]))),
	assert(mondo(c(p(1, 5), mare, []))),
	assert(mondo(c(p(2, 1), deserto, [aereo]))),
	assert(mondo(c(p(2, 2), deserto, [magnete]))),
	assert(mondo(c(p(2, 3), mare, []))),
	assert(mondo(c(p(2, 4), foresta, [carro]))),
	assert(mondo(c(p(2, 5), deserto, [magnete]))),
	assert(mondo(c(p(3, 1), cielo, []))),
	assert(mondo(c(p(3, 2), deserto, [magnete]))),
	assert(mondo(c(p(3, 3), cielo, []))),
	assert(mondo(c(p(3, 4), cielo, []))),
	assert(mondo(c(p(3, 5), cielo, []))),
	assert(mondo(c(p(4, 1), foresta, [carro]))),
	assert(mondo(c(p(4, 2), foresta, [magnete]))),
	assert(mondo(c(p(4, 3), cielo, []))),
	assert(mondo(c(p(4, 4), deserto, [magnete]))),
	assert(mondo(c(p(4, 5), foresta, [magnete]))),
	assert(mondo(c(p(5, 1), cielo, []))),
	assert(mondo(c(p(5, 2), foresta, []))),
        assert(mondo(c(p(5, 3), deserto, [barca]))),
	assert(mondo(c(p(5, 4), mare, []))),
	assert(mondo(c(p(5, 5), foresta, []))).

carica_mondo(mondo3) :-
	retractall(size(_)),
	retractall(mondo(_)),
	assert(size(5)),
	assert(mondo(c(p(1, 1), foresta, []))),
	assert(mondo(c(p(1, 2), foresta, []))),
	assert(mondo(c(p(1, 3), foresta, [aereo]))),
	assert(mondo(c(p(1, 4), deserto, [magnete]))),
	assert(mondo(c(p(1, 5), mare, []))),
	assert(mondo(c(p(2, 1), deserto, [aereo]))),
	assert(mondo(c(p(2, 2), deserto, [magnete]))),
	assert(mondo(c(p(2, 3), mare, []))),
	assert(mondo(c(p(2, 4), foresta, [carro]))),
	assert(mondo(c(p(2, 5), deserto, [magnete]))),
	assert(mondo(c(p(3, 1), cielo, []))),
	assert(mondo(c(p(3, 2), mare, []))),
	assert(mondo(c(p(3, 3), cielo, []))),
	assert(mondo(c(p(3, 4), cielo, []))),
	assert(mondo(c(p(3, 5), cielo, []))),
	assert(mondo(c(p(4, 1), foresta, [carro]))),
	assert(mondo(c(p(4, 2), foresta, [magnete]))),
	assert(mondo(c(p(4, 3), cielo, []))),
	assert(mondo(c(p(4, 4), deserto, [magnete]))),
	assert(mondo(c(p(4, 5), foresta, [magnete]))),
	assert(mondo(c(p(5, 1), cielo, []))),
	assert(mondo(c(p(5, 2), cielo, []))),
        assert(mondo(c(p(5, 3), deserto, [barca]))),
	assert(mondo(c(p(5, 4), mare, []))),
	assert(mondo(c(p(5, 5), foresta, []))).

carica_mondo(mondo_impossibile1) :-
        retractall(size(_)),
        retractall(mondo(_)),
        assert(size(5)),
        assert(mondo(c(p(1,1),foresta,[]))),
        assert(mondo(c(p(1,2),cielo,[]))),
        assert(mondo(c(p(1,3),deserto,[]))),
        assert(mondo(c(p(1,4),deserto,[barca]))),
        assert(mondo(c(p(1,5),cielo,[]))),
        assert(mondo(c(p(2,1),foresta,[barca,carro]))),
        assert(mondo(c(p(2,2),deserto,[]))),
        assert(mondo(c(p(2,3),cielo,[]))),
        assert(mondo(c(p(2,4),deserto,[]))),
        assert(mondo(c(p(2,5),deserto,[barca]))),
        assert(mondo(c(p(3,1),foresta,[]))),
        assert(mondo(c(p(3,2),foresta,[carro]))),
        assert(mondo(c(p(3,3),foresta,[magnete]))),
        assert(mondo(c(p(3,4),deserto,[]))),
        assert(mondo(c(p(3,5),deserto,[]))),
        assert(mondo(c(p(4,1),deserto,[magnete]))),
        assert(mondo(c(p(4,2),mare,[]))),
        assert(mondo(c(p(4,3),deserto,[]))),
        assert(mondo(c(p(4,4),deserto,[]))),
        assert(mondo(c(p(4,5),deserto,[]))),
        assert(mondo(c(p(5,1),mare,[]))),
        assert(mondo(c(p(5,2),foresta,[barca]))),
        assert(mondo(c(p(5,3),deserto,[barca]))),
        assert(mondo(c(p(5,4),foresta,[]))),
        assert(mondo(c(p(5,5),cielo,[]))).

carica_mondo(mondo_impossibile2) :-
        retractall(size(_)),
        retractall(mondo(_)),
        assert(size(10)),
        assert(mondo(c(p(1,1),deserto,[aereo]))),
        assert(mondo(c(p(1,2),foresta,[magnete]))),
        assert(mondo(c(p(1,3),cielo,[]))),
        assert(mondo(c(p(1,4),cielo,[]))),
        assert(mondo(c(p(1,5),deserto,[aereo,barca]))),
        assert(mondo(c(p(1,6),deserto,[aereo,barca]))),
        assert(mondo(c(p(1,7),deserto,[]))),
        assert(mondo(c(p(1,8),foresta,[carro]))),
        assert(mondo(c(p(1,9),deserto,[aereo]))),
        assert(mondo(c(p(1,10),foresta,[magnete]))),
        assert(mondo(c(p(2,1),mare,[]))),
        assert(mondo(c(p(2,2),cielo,[]))),
        assert(mondo(c(p(2,3),deserto,[]))),
        assert(mondo(c(p(2,4),cielo,[]))),
        assert(mondo(c(p(2,5),mare,[]))),
        assert(mondo(c(p(2,6),deserto,[aereo]))),
        assert(mondo(c(p(2,7),deserto,[aereo]))),
        assert(mondo(c(p(2,8),foresta,[]))),
        assert(mondo(c(p(2,9),foresta,[aereo,carro]))),
        assert(mondo(c(p(2,10),cielo,[]))),
        assert(mondo(c(p(3,1),mare,[]))),
        assert(mondo(c(p(3,2),cielo,[]))),
        assert(mondo(c(p(3,3),foresta,[magnete]))),
        assert(mondo(c(p(3,4),deserto,[aereo,barca]))),
        assert(mondo(c(p(3,5),cielo,[]))),
        assert(mondo(c(p(3,6),foresta,[carro]))),
        assert(mondo(c(p(3,7),cielo,[]))),
        assert(mondo(c(p(3,8),foresta,[carro]))),
        assert(mondo(c(p(3,9),deserto,[aereo]))),
        assert(mondo(c(p(3,10),foresta,[]))),
        assert(mondo(c(p(4,1),foresta,[barca]))),
        assert(mondo(c(p(4,2),mare,[]))),
        assert(mondo(c(p(4,3),deserto,[aereo]))),
        assert(mondo(c(p(4,4),mare,[]))),
        assert(mondo(c(p(4,5),foresta,[magnete]))),
        assert(mondo(c(p(4,6),mare,[]))),
        assert(mondo(c(p(4,7),deserto,[]))),
        assert(mondo(c(p(4,8),deserto,[]))),
        assert(mondo(c(p(4,9),deserto,[]))),
        assert(mondo(c(p(4,10),deserto,[]))),
        assert(mondo(c(p(5,1),cielo,[]))),
        assert(mondo(c(p(5,2),foresta,[aereo,carro]))),
        assert(mondo(c(p(5,3),foresta,[]))),
        assert(mondo(c(p(5,4),mare,[]))),
        assert(mondo(c(p(5,5),foresta,[barca]))),
        assert(mondo(c(p(5,6),foresta,[carro]))),
        assert(mondo(c(p(5,7),deserto,[]))),
        assert(mondo(c(p(5,8),mare,[]))),
        assert(mondo(c(p(5,9),foresta,[]))),
        assert(mondo(c(p(5,10),foresta,[]))),
        assert(mondo(c(p(6,1),foresta,[aereo]))),
        assert(mondo(c(p(6,2),deserto,[magnete]))),
        assert(mondo(c(p(6,3),deserto,[aereo]))),
        assert(mondo(c(p(6,4),mare,[]))),
        assert(mondo(c(p(6,5),cielo,[]))),
        assert(mondo(c(p(6,6),cielo,[]))),
        assert(mondo(c(p(6,7),foresta,[]))),
        assert(mondo(c(p(6,8),deserto,[aereo,barca]))),
        assert(mondo(c(p(6,9),deserto,[]))),
        assert(mondo(c(p(6,10),foresta,[]))),
        assert(mondo(c(p(7,1),deserto,[]))),
        assert(mondo(c(p(7,2),deserto,[barca]))),
        assert(mondo(c(p(7,3),foresta,[magnete]))),
        assert(mondo(c(p(7,4),foresta,[aereo]))),
        assert(mondo(c(p(7,5),cielo,[]))),
        assert(mondo(c(p(7,6),cielo,[]))),
        assert(mondo(c(p(7,7),cielo,[]))),
        assert(mondo(c(p(7,8),cielo,[]))),
        assert(mondo(c(p(7,9),deserto,[]))),
        assert(mondo(c(p(7,10),deserto,[]))),
        assert(mondo(c(p(8,1),mare,[]))),
        assert(mondo(c(p(8,2),foresta,[]))),
        assert(mondo(c(p(8,3),foresta,[]))),
        assert(mondo(c(p(8,4),cielo,[]))),
        assert(mondo(c(p(8,5),cielo,[]))),
        assert(mondo(c(p(8,6),foresta,[aereo]))),
        assert(mondo(c(p(8,7),deserto,[]))),
        assert(mondo(c(p(8,8),foresta,[]))),
        assert(mondo(c(p(8,9),foresta,[]))),
        assert(mondo(c(p(8,10),foresta,[magnete]))),
        assert(mondo(c(p(9,1),deserto,[]))),
        assert(mondo(c(p(9,2),mare,[]))),
        assert(mondo(c(p(9,3),foresta,[aereo,carro]))),
        assert(mondo(c(p(9,4),deserto,[barca]))),
        assert(mondo(c(p(9,5),deserto,[]))),
        assert(mondo(c(p(9,6),mare,[]))),
        assert(mondo(c(p(9,7),cielo,[]))),
        assert(mondo(c(p(9,8),deserto,[magnete]))),
        assert(mondo(c(p(9,9),cielo,[]))),
        assert(mondo(c(p(9,10),deserto,[]))),
        assert(mondo(c(p(10,1),deserto,[]))),
        assert(mondo(c(p(10,2),foresta,[]))),
        assert(mondo(c(p(10,3),foresta,[carro]))),
        assert(mondo(c(p(10,4),foresta,[]))),
        assert(mondo(c(p(10,5),mare,[]))),
        assert(mondo(c(p(10,6),deserto,[aereo]))),
        assert(mondo(c(p(10,7),deserto,[]))),
        assert(mondo(c(p(10,8),foresta,[]))),
        assert(mondo(c(p(10,9),mare,[]))),
        assert(mondo(c(p(10,10),cielo,[]))).
	
carica_mondo(mondo_interessante1) :-
        retractall(size(_)),
        retractall(mondo(_)),
        assert(size(5)),
        assert(mondo(c(p(1,1),cielo,[]))),
        assert(mondo(c(p(1,2),mare,[]))),
        assert(mondo(c(p(1,3),mare,[]))),
        assert(mondo(c(p(1,4),foresta,[carro]))),
        assert(mondo(c(p(1,5),deserto,[]))),
        assert(mondo(c(p(2,1),deserto,[]))),
        assert(mondo(c(p(2,2),foresta,[carro]))),
        assert(mondo(c(p(2,3),deserto,[]))),
        assert(mondo(c(p(2,4),deserto,[aereo]))),
        assert(mondo(c(p(2,5),deserto,[magnete]))),
        assert(mondo(c(p(3,1),deserto,[aereo]))),
        assert(mondo(c(p(3,2),cielo,[]))),
        assert(mondo(c(p(3,3),foresta,[magnete]))),
        assert(mondo(c(p(3,4),mare,[]))),
        assert(mondo(c(p(3,5),cielo,[]))),
        assert(mondo(c(p(4,1),foresta,[carro]))),
        assert(mondo(c(p(4,2),mare,[]))),
        assert(mondo(c(p(4,3),cielo,[]))),
        assert(mondo(c(p(4,4),deserto,[magnete]))),
        assert(mondo(c(p(4,5),deserto,[]))),
        assert(mondo(c(p(5,1),cielo,[]))),
        assert(mondo(c(p(5,2),foresta,[barca]))),
        assert(mondo(c(p(5,3),foresta,[magnete]))),
        assert(mondo(c(p(5,4),mare,[]))),
        assert(mondo(c(p(5,5),cielo,[]))).
	
carica_mondo(mondo_interessante2) :-
        retractall(size(_)),
        retractall(mondo(_)),
        assert(size(10)),
        assert(mondo(c(p(1,1),mare,[]))),
        assert(mondo(c(p(1,2),foresta,[]))),
        assert(mondo(c(p(1,3),mare,[]))),
        assert(mondo(c(p(1,4),mare,[]))),
        assert(mondo(c(p(1,5),deserto,[]))),
        assert(mondo(c(p(1,6),mare,[]))),
        assert(mondo(c(p(1,7),cielo,[]))),
        assert(mondo(c(p(1,8),foresta,[]))),
        assert(mondo(c(p(1,9),deserto,[]))),
        assert(mondo(c(p(1,10),mare,[]))),
        assert(mondo(c(p(2,1),foresta,[]))),
        assert(mondo(c(p(2,2),mare,[]))),
        assert(mondo(c(p(2,3),deserto,[aereo]))),
        assert(mondo(c(p(2,4),foresta,[barca]))),
        assert(mondo(c(p(2,5),foresta,[aereo]))),
        assert(mondo(c(p(2,6),mare,[]))),
        assert(mondo(c(p(2,7),deserto,[]))),
        assert(mondo(c(p(2,8),foresta,[]))),
        assert(mondo(c(p(2,9),mare,[]))),
        assert(mondo(c(p(2,10),foresta,[]))),
        assert(mondo(c(p(3,1),deserto,[]))),
        assert(mondo(c(p(3,2),mare,[]))),
        assert(mondo(c(p(3,3),cielo,[]))),
        assert(mondo(c(p(3,4),mare,[]))),
        assert(mondo(c(p(3,5),deserto,[barca]))),
        assert(mondo(c(p(3,6),deserto,[]))),
        assert(mondo(c(p(3,7),foresta,[carro]))),
        assert(mondo(c(p(3,8),deserto,[]))),
        assert(mondo(c(p(3,9),deserto,[]))),
        assert(mondo(c(p(3,10),deserto,[aereo]))),
        assert(mondo(c(p(4,1),foresta,[magnete]))),
        assert(mondo(c(p(4,2),mare,[]))),
        assert(mondo(c(p(4,3),cielo,[]))),
        assert(mondo(c(p(4,4),foresta,[magnete]))),
        assert(mondo(c(p(4,5),deserto,[barca]))),
        assert(mondo(c(p(4,6),cielo,[]))),
        assert(mondo(c(p(4,7),foresta,[]))),
        assert(mondo(c(p(4,8),foresta,[aereo]))),
        assert(mondo(c(p(4,9),foresta,[carro]))),
        assert(mondo(c(p(4,10),foresta,[]))),
        assert(mondo(c(p(5,1),deserto,[magnete]))),
        assert(mondo(c(p(5,2),foresta,[carro]))),
        assert(mondo(c(p(5,3),deserto,[magnete]))),
        assert(mondo(c(p(5,4),cielo,[]))),
        assert(mondo(c(p(5,5),foresta,[carro]))),
        assert(mondo(c(p(5,6),deserto,[magnete]))),
        assert(mondo(c(p(5,7),mare,[]))),
        assert(mondo(c(p(5,8),foresta,[aereo]))),
        assert(mondo(c(p(5,9),foresta,[magnete]))),
        assert(mondo(c(p(5,10),cielo,[]))),
        assert(mondo(c(p(6,1),cielo,[]))),
        assert(mondo(c(p(6,2),mare,[]))),
        assert(mondo(c(p(6,3),deserto,[magnete]))),
        assert(mondo(c(p(6,4),mare,[]))),
        assert(mondo(c(p(6,5),cielo,[]))),
        assert(mondo(c(p(6,6),mare,[]))),
        assert(mondo(c(p(6,7),deserto,[]))),
        assert(mondo(c(p(6,8),deserto,[magnete]))),
        assert(mondo(c(p(6,9),foresta,[aereo]))),
        assert(mondo(c(p(6,10),foresta,[magnete]))),
        assert(mondo(c(p(7,1),foresta,[barca,carro]))),
        assert(mondo(c(p(7,2),mare,[]))),
        assert(mondo(c(p(7,3),deserto,[]))),
        assert(mondo(c(p(7,4),cielo,[]))),
        assert(mondo(c(p(7,5),foresta,[carro]))),
        assert(mondo(c(p(7,6),deserto,[barca]))),
        assert(mondo(c(p(7,7),cielo,[]))),
        assert(mondo(c(p(7,8),deserto,[aereo]))),
        assert(mondo(c(p(7,9),deserto,[aereo]))),
        assert(mondo(c(p(7,10),mare,[]))),
        assert(mondo(c(p(8,1),foresta,[magnete]))),
        assert(mondo(c(p(8,2),cielo,[]))),
        assert(mondo(c(p(8,3),deserto,[]))),
        assert(mondo(c(p(8,4),cielo,[]))),
        assert(mondo(c(p(8,5),mare,[]))),
        assert(mondo(c(p(8,6),deserto,[magnete]))),
        assert(mondo(c(p(8,7),foresta,[magnete]))),
        assert(mondo(c(p(8,8),foresta,[magnete]))),
        assert(mondo(c(p(8,9),deserto,[magnete]))),
        assert(mondo(c(p(8,10),foresta,[]))),
        assert(mondo(c(p(9,1),mare,[]))),
        assert(mondo(c(p(9,2),cielo,[]))),
        assert(mondo(c(p(9,3),foresta,[]))),
        assert(mondo(c(p(9,4),cielo,[]))),
        assert(mondo(c(p(9,5),foresta,[aereo,carro]))),
        assert(mondo(c(p(9,6),cielo,[]))),
        assert(mondo(c(p(9,7),mare,[]))),
        assert(mondo(c(p(9,8),foresta,[aereo,barca]))),
        assert(mondo(c(p(9,9),foresta,[]))),
        assert(mondo(c(p(9,10),foresta,[magnete]))),
        assert(mondo(c(p(10,1),deserto,[barca]))),
        assert(mondo(c(p(10,2),foresta,[]))),
        assert(mondo(c(p(10,3),foresta,[]))),
        assert(mondo(c(p(10,4),foresta,[]))),
        assert(mondo(c(p(10,5),cielo,[]))),
        assert(mondo(c(p(10,6),cielo,[]))),
        assert(mondo(c(p(10,7),deserto,[magnete]))),
        assert(mondo(c(p(10,8),cielo,[]))),
        assert(mondo(c(p(10,9),deserto,[]))),
        assert(mondo(c(p(10,10),mare,[]))).


carica_mondo(mondo_problema_manhattan_migliorata1) :-
        retractall(size(_)),
        retractall(mondo(_)),
        assert(size(5)),
        assert(mondo(c(p(1,1),deserto,[aereo]))),
        assert(mondo(c(p(1,2),deserto,[aereo,barca]))),
        assert(mondo(c(p(1,3),cielo,[]))),
        assert(mondo(c(p(1,4),deserto,[barca]))),
        assert(mondo(c(p(1,5),cielo,[]))),
        assert(mondo(c(p(2,1),deserto,[]))),
        assert(mondo(c(p(2,2),foresta,[]))),
        assert(mondo(c(p(2,3),mare,[]))),
        assert(mondo(c(p(2,4),foresta,[]))),
        assert(mondo(c(p(2,5),foresta,[barca]))),
        assert(mondo(c(p(3,1),deserto,[]))),
        assert(mondo(c(p(3,2),deserto,[aereo]))),
        assert(mondo(c(p(3,3),foresta,[]))),
        assert(mondo(c(p(3,4),deserto,[]))),
        assert(mondo(c(p(3,5),foresta,[aereo]))),
        assert(mondo(c(p(4,1),deserto,[barca]))),
        assert(mondo(c(p(4,2),foresta,[]))),
        assert(mondo(c(p(4,3),foresta,[]))),
        assert(mondo(c(p(4,4),cielo,[]))),
        assert(mondo(c(p(4,5),deserto,[]))),
        assert(mondo(c(p(5,1),foresta,[aereo,carro]))),
        assert(mondo(c(p(5,2),foresta,[barca,carro]))),
        assert(mondo(c(p(5,3),foresta,[carro]))),
        assert(mondo(c(p(5,4),cielo,[]))),
        assert(mondo(c(p(5,5),mare,[]))).

carica_mondo(mondo_problema_manhattan_migliorata2) :-
        retractall(size(_)),
        retractall(mondo(_)),
        assert(size(10)),
        assert(mondo(c(p(1,1),deserto,[aereo,barca]))),
        assert(mondo(c(p(1,2),foresta,[magnete]))),
        assert(mondo(c(p(1,3),deserto,[barca]))),
        assert(mondo(c(p(1,4),foresta,[carro]))),
        assert(mondo(c(p(1,5),deserto,[barca]))),
        assert(mondo(c(p(1,6),foresta,[aereo]))),
        assert(mondo(c(p(1,7),deserto,[aereo,barca]))),
        assert(mondo(c(p(1,8),foresta,[]))),
        assert(mondo(c(p(1,9),deserto,[aereo]))),
        assert(mondo(c(p(1,10),deserto,[]))),
        assert(mondo(c(p(2,1),deserto,[aereo]))),
        assert(mondo(c(p(2,2),cielo,[]))),
        assert(mondo(c(p(2,3),cielo,[]))),
        assert(mondo(c(p(2,4),foresta,[]))),
        assert(mondo(c(p(2,5),cielo,[]))),
        assert(mondo(c(p(2,6),foresta,[]))),
        assert(mondo(c(p(2,7),deserto,[]))),
        assert(mondo(c(p(2,8),mare,[]))),
        assert(mondo(c(p(2,9),mare,[]))),
        assert(mondo(c(p(2,10),cielo,[]))),
        assert(mondo(c(p(3,1),deserto,[]))),
        assert(mondo(c(p(3,2),foresta,[aereo]))),
        assert(mondo(c(p(3,3),foresta,[aereo,carro]))),
        assert(mondo(c(p(3,4),deserto,[barca]))),
        assert(mondo(c(p(3,5),cielo,[]))),
        assert(mondo(c(p(3,6),foresta,[]))),
        assert(mondo(c(p(3,7),deserto,[]))),
        assert(mondo(c(p(3,8),mare,[]))),
        assert(mondo(c(p(3,9),deserto,[aereo,barca]))),
        assert(mondo(c(p(3,10),deserto,[magnete]))),
        assert(mondo(c(p(4,1),foresta,[magnete]))),
        assert(mondo(c(p(4,2),foresta,[aereo,barca]))),
        assert(mondo(c(p(4,3),foresta,[aereo]))),
        assert(mondo(c(p(4,4),mare,[]))),
        assert(mondo(c(p(4,5),deserto,[]))),
        assert(mondo(c(p(4,6),mare,[]))),
        assert(mondo(c(p(4,7),foresta,[barca,carro]))),
        assert(mondo(c(p(4,8),deserto,[aereo,barca]))),
        assert(mondo(c(p(4,9),cielo,[]))),
        assert(mondo(c(p(4,10),cielo,[]))),
        assert(mondo(c(p(5,1),deserto,[]))),
        assert(mondo(c(p(5,2),cielo,[]))),
        assert(mondo(c(p(5,3),foresta,[]))),
        assert(mondo(c(p(5,4),cielo,[]))),
        assert(mondo(c(p(5,5),cielo,[]))),
        assert(mondo(c(p(5,6),foresta,[carro]))),
        assert(mondo(c(p(5,7),deserto,[aereo]))),
        assert(mondo(c(p(5,8),cielo,[]))),
        assert(mondo(c(p(5,9),foresta,[]))),
        assert(mondo(c(p(5,10),foresta,[aereo]))),
        assert(mondo(c(p(6,1),cielo,[]))),
        assert(mondo(c(p(6,2),deserto,[aereo]))),
        assert(mondo(c(p(6,3),deserto,[barca]))),
        assert(mondo(c(p(6,4),mare,[]))),
        assert(mondo(c(p(6,5),deserto,[aereo]))),
        assert(mondo(c(p(6,6),foresta,[barca]))),
        assert(mondo(c(p(6,7),foresta,[]))),
        assert(mondo(c(p(6,8),cielo,[]))),
        assert(mondo(c(p(6,9),deserto,[barca]))),
        assert(mondo(c(p(6,10),deserto,[barca]))),
        assert(mondo(c(p(7,1),foresta,[]))),
        assert(mondo(c(p(7,2),deserto,[]))),
        assert(mondo(c(p(7,3),foresta,[]))),
        assert(mondo(c(p(7,4),deserto,[aereo]))),
        assert(mondo(c(p(7,5),deserto,[]))),
        assert(mondo(c(p(7,6),foresta,[magnete]))),
        assert(mondo(c(p(7,7),mare,[]))),
        assert(mondo(c(p(7,8),foresta,[magnete]))),
        assert(mondo(c(p(7,9),mare,[]))),
        assert(mondo(c(p(7,10),mare,[]))),
        assert(mondo(c(p(8,1),foresta,[]))),
        assert(mondo(c(p(8,2),mare,[]))),
        assert(mondo(c(p(8,3),foresta,[aereo,barca]))),
        assert(mondo(c(p(8,4),cielo,[]))),
        assert(mondo(c(p(8,5),deserto,[barca]))),
        assert(mondo(c(p(8,6),foresta,[]))),
        assert(mondo(c(p(8,7),deserto,[aereo]))),
        assert(mondo(c(p(8,8),deserto,[]))),
        assert(mondo(c(p(8,9),deserto,[]))),
        assert(mondo(c(p(8,10),cielo,[]))),
        assert(mondo(c(p(9,1),foresta,[aereo,barca]))),
        assert(mondo(c(p(9,2),deserto,[]))),
        assert(mondo(c(p(9,3),deserto,[barca]))),
        assert(mondo(c(p(9,4),deserto,[aereo]))),
        assert(mondo(c(p(9,5),deserto,[aereo]))),
        assert(mondo(c(p(9,6),mare,[]))),
        assert(mondo(c(p(9,7),foresta,[magnete]))),
        assert(mondo(c(p(9,8),mare,[]))),
        assert(mondo(c(p(9,9),deserto,[barca]))),
        assert(mondo(c(p(9,10),deserto,[]))),
        assert(mondo(c(p(10,1),foresta,[barca]))),
        assert(mondo(c(p(10,2),cielo,[]))),
        assert(mondo(c(p(10,3),cielo,[]))),
        assert(mondo(c(p(10,4),foresta,[carro]))),
        assert(mondo(c(p(10,5),cielo,[]))),
        assert(mondo(c(p(10,6),cielo,[]))),
        assert(mondo(c(p(10,7),cielo,[]))),
        assert(mondo(c(p(10,8),foresta,[]))),
        assert(mondo(c(p(10,9),foresta,[aereo,barca]))),
        assert(mondo(c(p(10,10),cielo,[]))).
